version: '3.4'

services:
  ui:
    build: ui
    volumes:
      - './ui:/app'
    environment:
      - 'NODE_ENV=dev'
      - 'EXTERNAL_PORT=${UI_PORT}'
    command: /bin/bash 
    ports:
      - '${UI_PORT}:${UI_PORT}'
